apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-loadtest-deployment
  namespace: k6-loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-loadtest
  template:
    metadata:
      labels:
        app: k6-loadtest
    spec:
      containers:
        - name: k6
          image: ${REGISTRY}/${IMAGE}:${TAG}
          command:
            - k6
            - run
          args:
            - -e
            - ORDER_HOST=order-api-app-service.order-api-app.svc.cluster.local
            - -e
            - ORDER_PORT=8080
            - -e
            - K6_WEB_DASHBOARD=true
            - -e
            - K6_WEB_DASHBOARD_PERIOD=1s
            - script.js
            - --vus
            - '20'
            - --duration
            - 3600s
          imagePullPolicy: IfNotPresent
