apiVersion: v1
kind: Service
metadata:
  name: k6-service
  namespace: k6-loadtest
spec:
  type: NodePort
  selector:
    app: k6-loadtest
  ports:
    - protocol: TCP
      port: 5665
      targetPort: 5665
      nodePort: 30002
