apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-database-deployment
  namespace: order-api-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api-database
  template:
    metadata:
      labels:
        app: order-api-database
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: order-api-database-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              value: orderapi
            - name: POSTGRES_USER
              value: orderapi
            - name: POSTGRES_DB
              value: orderapi
      volumes:
        - name: order-api-database-storage
          persistentVolumeClaim:
            claimName: order-api-database-pvc
