apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-api-database-pvc
  namespace: order-api-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
