apiVersion: v1
kind: Service
metadata:
  name: order-api-database-service
  namespace: order-api-database
spec:
  type: NodePort
  selector:
    app: order-api-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30002
