apiVersion: v1
kind: Pod
metadata:
  name: order-api-migration-pod
  namespace: order-api-migration
spec:
  restartPolicy: OnFailure
  containers:
    - name: order-api-migration-pod
      image: ${REGISTRY}/${IMAGE}:${TAG}
      args:
        - --url=jdbc:postgresql://order-api-database-service.order-api-database.svc.cluster.local:5432/orderapi?currentSchema=public
        - --changeLogFile=./changelog/changelog.yaml
        - --username=orderapi
        - --password=orderapi
        - update
      imagePullPolicy: IfNotPresent
