replicaCount: 2

wait:
  image:
    repository: busybox
    pullPolicy: Always
    tag: latest

migration:
  image:
    repository: rogeriofbrito/order-api-migration
    pullPolicy: Always
    tag: latest

orderApi:
  image:
    repository: rogeriofbrito/order-api
    pullPolicy: Always
    tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /v1/health #TODO: change to /v1/liveness
    port: http

readinessProbe:
  httpGet:
    path: /v1/health #TODO: change to /v1/readiness
    port: http

configs:
  PORT: "8080"

secrets:
  DATABASE_HOST: ""
  DATABASE_PORT: ""
  DATABASE_NAME: ""
  DATABASE_USER: ""
  DATABASE_PASSWORD: ""
