apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.users.root.name }}
  labels:
    {{- include "cnpg.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.users.root.secrets.username }}"
  password: "{{ .Values.users.root.secrets.password }}"
