{
 "title": "Echo Framework Processes",
 "description": "Dashboard for applications that use https://github.com/globocom/echo-prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(echo_requests_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(echo_requests_total,instance)"
    }
   },
   {
    "name": "url",
    "label": "url",
    "query": {
     "query": "label_values(echo_requests_total,url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic - Req/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[2m])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic - Req/s by url",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[2m])) by (job, method, url)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{url}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Errors - % (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$url\", status=\"5xx\"}[5m])) by (job)/sum(rate(echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{url}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors - % by url (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$url\", status=\"5xx\"}[5m])) by (job, method, url)/sum(rate(echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])) by (job, method, url)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{url}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Latêncy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Latency - General",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])))",
     "legendFormat": "{{ job }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])))",
     "legendFormat": "{{ job }} - p99"
    }
   ]
  },
  {
   "title": "Latency by url",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, method, url, le) (rate(echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{ url }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, method, url, le) (rate(echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])))",
     "legendFormat": "{{ job }} - {{ method }} {{ url }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, method, url, le) (rate(echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])))",
     "legendFormat": "{{ job }} - {{ method }} {{ url }} - p99"
    }
   ]
  },
  {
   "title": "Latency by instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, instance, le) (rate(echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ instance }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, instance, le) (rate(echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate(echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$url\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p99"
    }
   ]
  }
 ]
}