apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "order-api.fullname" . }}
  labels:
    {{- include "order-api.labels" . | nindent 4 }}
data:
  {{- with .Values.secrets }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
