apiVersion: v1
kind: Pod
metadata:
  name: litmus-init-pod
  namespace: litmus
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: wait-for-litmus
      image: localhost:5000/litmusctl:latest
      command:
        - sh
        - '-c'
        - until ./litmusctl config set-account -e http://chaos-litmus-frontend-service.litmus.svc.cluster.local:9091 -u admin -p litmus --non-interactive=true && ./litmusctl get projects -o json; do echo waiting for litmus; sleep 2; done;
      imagePullPolicy: IfNotPresent
  containers:
    - name: litmus-init-pod
      image: ${REGISTRY}/${IMAGE}:${TAG}
      imagePullPolicy: IfNotPresent
