apiVersion: v1
kind: Pod
metadata:
  name: litmus-init-pod
  namespace: litmus
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: wait-for-litmus
      image: busybox:latest
      command:
        - sh
        - '-c'
        - until nc -z -v -w30 chaos-litmus-frontend-service.litmus.svc.cluster.local 9091; do echo waiting for litmus; sleep 2; done;
      imagePullPolicy: IfNotPresent
  containers:
    - name: litmus-init-pod
      image: ${REGISTRY}/${IMAGE}:${TAG}
      imagePullPolicy: IfNotPresent
