apiVersion: v1
kind: Service
metadata:
  name: order-api-app-service
  namespace: order-api-app
spec:
  type: NodePort
  selector:
    app: order-api-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
