kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: pod-autoscaler
  namespace: litmus
  creationTimestamp: null
  labels:
    infra_id: aabdce1d-143a-432c-80c5-d505ed5def13
    revision_id: 258a5cef-cd6f-4a73-ba1a-0a2c85733ceb
    workflow_id: 898dbed0-7b17-4c19-a783-4d8d44fb7fbb
    workflows.argoproj.io/controller-instanceid: aabdce1d-143a-432c-80c5-d505ed5def13
spec:
  templates:
    - name: exp
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-faults
            template: install-chaos-faults
            arguments: {}
        - - name: pod-autoscaler-qvc
            template: pod-autoscaler-qvc
            arguments: {}
        - - name: cleanup-chaos-resources
            template: cleanup-chaos-resources
            arguments: {}
    - name: install-chaos-faults
      inputs:
        artifacts:
          - name: pod-autoscaler-qvc
            path: /tmp/pod-autoscaler-qvc.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Scale the application replicas and test the node autoscaling on cluster
                kind: ChaosExperiment

                metadata:
                  name: pod-autoscaler
                  labels:
                    name: pod-autoscaler
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 3.6.1
                spec:
                  definition:
                    scope: Cluster
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - statefulsets
                        verbs:
                          - list
                          - get
                          - patch
                          - update
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.6.1
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-autoscaler
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: REPLICA_COUNT
                        value: "5"
                      - name: DEFAULT_HEALTH_CHECK
                        value: "false"
                    labels:
                      name: pod-autoscaler
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 3.6.1
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.11.0
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/ -n {{workflow.parameters.adminModeNamespace}}
            && sleep 30
        resources: {}
    - name: cleanup-chaos-resources
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.11.0
        command:
          - sh
          - -c
        args:
          - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
            {{workflow.parameters.adminModeNamespace}}
        resources: {}
    - name: pod-autoscaler-qvc
      inputs:
        artifacts:
          - name: pod-autoscaler-qvc
            path: /tmp/chaosengine-pod-autoscaler-qvc.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    workflow_run_id: "{{ workflow.uid }}"
                    workflow_name: pod-autoscaler
                  annotations:
                    probeRef: '[{"name":"fake","mode":"SOT"}]'
                  generateName: pod-autoscaler-qvc
                spec:
                  engineState: active
                  auxiliaryAppInfo: ""
                  appinfo:
                    appns: app
                    applabel: app=order-api
                    appkind: deployment
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-autoscaler
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "180"
                            - name: RAMP_TIME
                              value: ""
                            - name: REPLICA_COUNT
                              value: "6"
                            - name: DEFAULT_HEALTH_CHECK
                              value: "false"
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: docker.io/litmuschaos/litmus-checker:2.11.0
        args:
          - -file=/tmp/chaosengine-pod-autoscaler-qvc.yaml
          - -saveName=/tmp/engine-name
        resources: {}
  entrypoint: exp
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  serviceAccountName: argo-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
status:
  startedAt: null
  finishedAt: null
