kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: pod-http-status-code-not-works-with-port-forward
  namespace: litmus
  creationTimestamp: null
  labels:
    infra_id: aabdce1d-143a-432c-80c5-d505ed5def13
    revision_id: 325b8a89-b2ea-4119-94f0-26e1de2256ff
    workflow_id: ffe8c63d-d3bd-44b8-9eaf-8d3259a069cd
    workflows.argoproj.io/controller-instanceid: aabdce1d-143a-432c-80c5-d505ed5def13
spec:
  templates:
    - name: exp
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-faults
            template: install-chaos-faults
            arguments: {}
        - - name: pod-http-status-code-cli
            template: pod-http-status-code-cli
            arguments: {}
        - - name: cleanup-chaos-resources
            template: cleanup-chaos-resources
            arguments: {}
    - name: install-chaos-faults
      inputs:
        artifacts:
          - name: pod-http-status-code-cli
            path: /tmp/pod-http-status-code-cli.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: >
                    It injects chaos inside the pod which modifies the status code of the
                    response from the provided application server to desired status code
                    provided by the user and reverts after a specified duration
                kind: ChaosExperiment

                metadata:
                  name: pod-http-status-code
                  labels:
                    name: pod-http-status-code
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 3.6.1
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - statefulsets
                          - replicasets
                          - daemonsets
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - apps.openshift.io
                        resources:
                          - deploymentconfigs
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - ""
                        resources:
                          - replicationcontrollers
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - argoproj.io
                        resources:
                          - rollouts
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.6.1
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-http-status-code
                    command:
                      - /bin/bash
                    env:
                      - name: TARGET_CONTAINER
                        value: ""
                      - name: LIB_IMAGE
                        value: litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.6.1
                      - name: STATUS_CODE
                        value: "500"
                      - name: MODIFY_RESPONSE_BODY
                        value: "true"
                      - name: RESPONSE_BODY
                        value: Error
                      - name: CONTENT_ENCODING
                        value: ""
                      - name: CONTENT_TYPE
                        value: text/plain
                      - name: TARGET_SERVICE_PORT
                        value: "8080"
                      - name: TOXICITY
                        value: "100"
                      - name: PROXY_PORT
                        value: "8081"
                      - name: NETWORK_INTERFACE
                        value: eth0@if99
                      - name: TOTAL_CHAOS_DURATION
                        value: "600"
                      - name: RAMP_TIME
                        value: ""
                      - name: DEFAULT_HEALTH_CHECK
                        value: "false"
                      - name: PODS_AFFECTED_PERC
                        value: "100"
                      - name: TARGET_PODS
                        value: ""
                      - name: CONTAINER_RUNTIME
                        value: containerd
                      - name: SOCKET_PATH
                        value: /run/containerd/containerd.sock
                      - name: NODE_LABEL
                        value: ""
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: pod-http-status-code
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 3.6.1
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.11.0
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/ -n {{workflow.parameters.adminModeNamespace}}
            && sleep 30
        resources: {}
    - name: cleanup-chaos-resources
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.11.0
        command:
          - sh
          - -c
        args:
          - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
            {{workflow.parameters.adminModeNamespace}}
        resources: {}
    - name: pod-http-status-code-cli
      inputs:
        artifacts:
          - name: pod-http-status-code-cli
            path: /tmp/chaosengine-pod-http-status-code-cli.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    workflow_run_id: "{{ workflow.uid }}"
                    workflow_name: pod-http-status-code-not-works-with-port-forward
                  annotations:
                    probeRef: '[{"name":"fake","mode":"SOT"}]'
                  generateName: pod-http-status-code-cli
                spec:
                  engineState: active
                  appinfo:
                    appns: app
                    applabel: app=order-api
                    appkind: deployment
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-http-status-code
                      spec:
                        components:
                          env:
                            - name: TARGET_CONTAINER
                              value: ""
                            - name: LIB_IMAGE
                              value: litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.6.1
                            - name: STATUS_CODE
                              value: "500"
                            - name: MODIFY_RESPONSE_BODY
                              value: "true"
                            - name: RESPONSE_BODY
                              value: Error from litmus
                            - name: CONTENT_ENCODING
                              value: ""
                            - name: CONTENT_TYPE
                              value: text/plain
                            - name: TARGET_SERVICE_PORT
                              value: "8080"
                            - name: TOXICITY
                              value: "100"
                            - name: PROXY_PORT
                              value: "8081"
                            - name: NETWORK_INTERFACE
                              value: eth0
                            - name: TOTAL_CHAOS_DURATION
                              value: "600"
                            - name: RAMP_TIME
                              value: ""
                            - name: DEFAULT_HEALTH_CHECK
                              value: "false"
                            - name: PODS_AFFECTED_PERC
                              value: "100"
                            - name: TARGET_PODS
                              value: ""
                            - name: CONTAINER_RUNTIME
                              value: containerd
                            - name: SOCKET_PATH
                              value: /run/containerd/containerd.sock
                            - name: NODE_LABEL
                              value: ""
                            - name: SEQUENCE
                              value: parallel
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: docker.io/litmuschaos/litmus-checker:2.11.0
        args:
          - -file=/tmp/chaosengine-pod-http-status-code-cli.yaml
          - -saveName=/tmp/engine-name
        resources: {}
  entrypoint: exp
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  serviceAccountName: argo-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
status:
  startedAt: null
  finishedAt: null
